version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  flask_api:
    build: ./API
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./API:/app   # 可選：熱重載 Flask 用

  sensor:
    build: ./Sensor
    depends_on:
      - flask_api
